// 5-letter words with meanings: 730 common English words (2 years of daily Wordle)
// Each refresh picks a random word from this list - no tracking needed
// Words are sorted by corpus frequency, supplemented from WordNet
// All words have clean, non-offensive, common-language definitions

export interface WordEntry {
  word: string;
  meaning: string;
}

const WORDS: WordEntry[] = [
  { word: "first", meaning: "the first or highest in an ordering or series" },
  { word: "state", meaning: "the territory occupied by one of the constituent administrative districts of a nation" },
  { word: "world", meaning: "everything that exists anywhere" },
  { word: "still", meaning: "a static photograph (especially one taken from a movie and used for advertising purposes)" },
  { word: "never", meaning: "not ever; at no time in the past or future" },
  { word: "might", meaning: "physical strength" },
  { word: "great", meaning: "relatively large in size or number or extent; larger than others of its kind" },
  { word: "right", meaning: "the piece of ground in the outfield on the catcher's right" },
  { word: "three", meaning: "the cardinal number that is the sum of one and one and one" },
  { word: "house", meaning: "a dwelling that serves as living quarters for one or more families" },
  { word: "place", meaning: "a point located with respect to surface features of some region" },
  { word: "small", meaning: "the slender part of the back" },
  { word: "found", meaning: "food and lodging provided in addition to money" },
  { word: "every", meaning: "(used of count nouns) each and all of the members of a group considered singly and without exception" },
  { word: "water", meaning: "once thought to be one of four elements composing the universe (Empedocles)" },
  { word: "think", meaning: "an instance of deliberate thinking" },
  { word: "night", meaning: "the time after sunset and before sunrise while it is dark outside" },
  { word: "going", meaning: "the act of departing" },
  { word: "later", meaning: "coming at a subsequent time or stage" },
  { word: "point", meaning: "a geometric element that has position but no extension" },
  { word: "group", meaning: "any number of entities (members) considered as a unit" },
  { word: "young", meaning: "any immature animal" },
  { word: "given", meaning: "an assumption that is taken for granted" },
  { word: "order", meaning: "a degree in a continuum of size or quantity" },
  { word: "often", meaning: "many times at short intervals" },
  { word: "early", meaning: "being or occurring at an early stage of development" },
  { word: "white", meaning: "(board games) the lighter pieces" },
  { word: "large", meaning: "a garment size for a large person" },
  { word: "along", meaning: "with a forward motion" },
  { word: "least", meaning: "something that is of no importance" },
  { word: "power", meaning: "possession of controlling influence" },
  { word: "light", meaning: "(physics) electromagnetic radiation that can produce a visual sensation" },
  { word: "thing", meaning: "a special situation" },
  { word: "sense", meaning: "a general conscious awareness" },
  { word: "whole", meaning: "all of something including all its component elements or parts" },
  { word: "times", meaning: "a more or less definite period of time now or previously present" },
  { word: "human", meaning: "characteristic of humanity" },
  { word: "local", meaning: "public transport consisting of a bus or train that stops at all stations or stops" },
  { word: "today", meaning: "the present time or age" },
  { word: "quite", meaning: "to a degree (not used with a negative)" },
  { word: "death", meaning: "the event of dying or departure from life" },
  { word: "field", meaning: "a piece of land cleared of trees and usually enclosed" },
  { word: "money", meaning: "the most common medium of exchange; functions as legal tender" },
  { word: "major", meaning: "a university student who is studying a particular field as the principal subject" },
  { word: "study", meaning: "a detailed critical inspection" },
  { word: "known", meaning: "know how to do or perform something" },
  { word: "south", meaning: "the cardinal compass point that is at 180 degrees" },
  { word: "board", meaning: "a committee having supervisory powers" },
  { word: "close", meaning: "the temporal end; the concluding time" },
  { word: "court", meaning: "a room in which a lawcourt sits" },
  { word: "force", meaning: "a powerful effect or influence" },
  { word: "voice", meaning: "the distinctive quality or pitch or condition of a person's speech" },
  { word: "woman", meaning: "an adult female person (as opposed to a man)" },
  { word: "front", meaning: "the side that is forward or prominent" },
  { word: "clear", meaning: "the state of being free of suspicion" },
  { word: "music", meaning: "any agreeable (pleasing and harmonious) sounds" },
  { word: "party", meaning: "an organization to gain political power" },
  { word: "child", meaning: "a young person of either sex" },
  { word: "level", meaning: "a position on a scale of intensity or amount or quality" },
  { word: "short", meaning: "accidental contact between two points in an electric circuit that have a potential difference" },
  { word: "stood", meaning: "be standing; be upright" },
  { word: "total", meaning: "the whole amount" },
  { word: "class", meaning: "a collection of things sharing a common attribute" },
  { word: "north", meaning: "the cardinal compass point that is at 0 or 360 degrees" },
  { word: "leave", meaning: "the period of time during which you are absent from work or duty" },
  { word: "sound", meaning: "the particular auditory effect produced by a given cause" },
  { word: "black", meaning: "total absence of light" },
  { word: "value", meaning: "a numerical quantity measured or assigned or computed" },
  { word: "peace", meaning: "the state prevailing during the absence of war" },
  { word: "table", meaning: "a set of data arranged in rows and columns" },
  { word: "alone", meaning: "isolated from others" },
  { word: "third", meaning: "one of three equal parts of a divisible whole" },
  { word: "basis", meaning: "a relation that provides the foundation for something" },
  { word: "space", meaning: "the unlimited expanse in which everything is located" },
  { word: "union", meaning: "an organization of employees formed to bargain with the employer" },
  { word: "wrote", meaning: "produce a literary work" },
  { word: "brown", meaning: "an orange of low brightness and saturation" },
  { word: "stage", meaning: "any distinct time period in a sequence of events" },
  { word: "heart", meaning: "the locus of feelings and intuitions" },
  { word: "miles", meaning: "a unit of length equal to 1,760 yards or 5,280 feet; exactly 1609.344 meters" },
  { word: "added", meaning: "state or say further" },
  { word: "basic", meaning: "(usually plural) a necessary commodity for which demand is constant" },
  { word: "tried", meaning: "make an effort or attempt" },
  { word: "shown", meaning: "give an exhibition of to an interested audience" },
  { word: "river", meaning: "a large natural stream of water (larger than a creek)" },
  { word: "bring", meaning: "take something or somebody with oneself somewhere" },
  { word: "floor", meaning: "the inside lower horizontal surface (as of a room, hallway, tent, or other structure)" },
  { word: "paper", meaning: "a material made of cellulose pulp derived mainly from wood or rags or certain grasses" },
  { word: "range", meaning: "an area in which something acts or operates or has power or control:" },
  { word: "final", meaning: "the final match between the winners of all previous matches in an elimination tournament" },
  { word: "start", meaning: "the beginning of anything" },
  { word: "story", meaning: "a piece of fiction that narrates a chain of related events" },
  { word: "issue", meaning: "an important question that is in dispute and must be settled" },
  { word: "needs", meaning: "a condition requiring relief" },
  { word: "earth", meaning: "the 3rd planet from the sun; the planet we live on" },
  { word: "labor", meaning: "a social class comprising those who do manual labor or work for wages" },
  { word: "stand", meaning: "a support or foundation" },
  { word: "stock", meaning: "the merchandise that a shop has on hand" },
  { word: "ready", meaning: "poised for action" },
  { word: "trade", meaning: "the skilled practice of a practical occupation" },
  { word: "moral", meaning: "the significance of a story or event" },
  { word: "color", meaning: "a visual attribute of things that results from the light they emit or transmit or reflect" },
  { word: "comes", meaning: "the thick white fluid containing spermatozoa that is ejaculated by the male genital tract" },
  { word: "trial", meaning: "the act of testing something" },
  { word: "cause", meaning: "events that provide the generative force that is the origin of something" },
  { word: "month", meaning: "one of the twelve divisions of the calendar year" },
  { word: "works", meaning: "buildings for carrying on industrial labor" },
  { word: "piece", meaning: "a separate part of a whole" },
  { word: "wrong", meaning: "that which is contrary to the principles of justice or law" },
  { word: "press", meaning: "the state of demanding notice or attention" },
  { word: "hotel", meaning: "a building where travelers can pay for lodging and meals and other services" },
  { word: "truth", meaning: "a fact that has been verified" },
  { word: "plant", meaning: "buildings for carrying on industrial labor" },
  { word: "lower", meaning: "the lower of two berths" },
  { word: "daily", meaning: "a newspaper that is published every day" },
  { word: "blood", meaning: "temperament or disposition" },
  { word: "march", meaning: "the month following February and preceding April" },
  { word: "radio", meaning: "medium for communication" },
  { word: "based", meaning: "use as a basis for; found on" },
  { word: "chief", meaning: "the head of a tribe or clan" },
  { word: "image", meaning: "an iconic mental representation" },
  { word: "horse", meaning: "solid-hoofed herbivorous quadruped domesticated since prehistoric times" },
  { word: "green", meaning: "green color or pigment; resembling the color of growing grass" },
  { word: "lived", meaning: "inhabit or live in; be an inhabitant of" },
  { word: "doubt", meaning: "the state of being unsure of something" },
  { word: "plane", meaning: "an aircraft that has a fixed wing and is powered by propellers or jets" },
  { word: "seven", meaning: "the cardinal number that is the sum of six and one" },
  { word: "staff", meaning: "personnel who assist their superior in carrying out an assigned task" },
  { word: "faith", meaning: "a strong belief in a supernatural power or powers that control human destiny" },
  { word: "corps", meaning: "an army unit usually consisting of two or more divisions and their support" },
  { word: "heavy", meaning: "a serious (or tragic) role in a play" },
  { word: "speak", meaning: "express in speech" },
  { word: "ahead", meaning: "having the leading position or higher score in a contest" },
  { word: "visit", meaning: "the act of going to see some person or place or thing for a short time" },
  { word: "price", meaning: "the amount of money needed to purchase something" },
  { word: "negro", meaning: "a person with dark skin who comes from Africa (or whose ancestors came from Africa)" },
  { word: "serve", meaning: "(sports) a stroke that puts the ball in play" },
  { word: "scene", meaning: "the place where some action occurs" },
  { word: "write", meaning: "produce a literary work" },
  { word: "drive", meaning: "the act of applying force to propel something" },
  { word: "reach", meaning: "the limits within which something can be effective" },
  { word: "eight", meaning: "the cardinal number that is the sum of seven and one" },
  { word: "spent", meaning: "pass time in a specific way" },
  { word: "built", meaning: "make by combining materials and parts" },
  { word: "mouth", meaning: "the opening through which food is taken in and vocalizations emerge" },
  { word: "teeth", meaning: "the kind and number and arrangement of teeth (collectively) in a person or animal" },
  { word: "james", meaning: "a New Testament book attributed to Saint James the Apostle" },
  { word: "meant", meaning: "mean or intend to express or convey" },
  { word: "sides", meaning: "one of two or more contesting groups" },
  { word: "glass", meaning: "a brittle transparent solid with irregular atomic structure" },
  { word: "claim", meaning: "an assertion of a right (as to money or property)" },
  { word: "fight", meaning: "a hostile meeting of opposing military forces in the course of a war" },
  { word: "happy", meaning: "enjoying or showing or marked by joy or pleasure" },
  { word: "share", meaning: "assets belonging to or due to or contributed by an individual person or group" },
  { word: "style", meaning: "how something is done or how it happens" },
  { word: "usual", meaning: "commonly encountered" },
  { word: "funds", meaning: "assets in the form of money" },
  { word: "worth", meaning: "an indefinite quantity of something having a specified value" },
  { word: "older", meaning: "advanced in years; (`aged' is pronounced as two syllables)" },
  { word: "civil", meaning: "applying to ordinary citizens as contrasted with the military" },
  { word: "dance", meaning: "an artistic form of nonverbal communication" },
  { word: "equal", meaning: "be identical or equivalent to" },
  { word: "noted", meaning: "make mention of" },
  { word: "break", meaning: "some abrupt occurrence that interrupts an ongoing activity" },
  { word: "carry", meaning: "the act of carrying something" },
  { word: "check", meaning: "a written order directing a bank to pay money" },
  { word: "cover", meaning: "a covering that serves to conceal or shelter something" },
  { word: "enemy", meaning: "an opposing military force" },
  { word: "fixed", meaning: "restore by replacing a part or putting together what is torn or broken" },
  { word: "spoke", meaning: "support consisting of a radial member of a wheel joining the hub to the rim" },
  { word: "touch", meaning: "the event of something coming in contact with the body" },
  { word: "build", meaning: "constitution of the human body" },
  { word: "shape", meaning: "any spatial attributes (especially as defined by outline)" },
  { word: "aware", meaning: "bearing in mind; attentive to" },
  { word: "begin", meaning: "take the first step or steps in carrying out an action" },
  { word: "broad", meaning: "slang term for a woman" },
  { word: "learn", meaning: "gain knowledge or skills" },
  { word: "sight", meaning: "an instance of visual perception" },
  { word: "speed", meaning: "distance travelled per unit time" },
  { word: "drink", meaning: "a single serving of a beverage" },
  { word: "fresh", meaning: "recently made, produced, or harvested" },
  { word: "train", meaning: "public transport provided by a line of railway cars coupled together and drawn by a locomotive" },
  { word: "youth", meaning: "a young person (especially a young man or boy)" },
  { word: "event", meaning: "something that happens at a given place and time" },
  { word: "index", meaning: "a numerical scale used to compare variables with one another or with some reference number" },
  { word: "watch", meaning: "a small portable timepiece" },
  { word: "fully", meaning: "sufficiently; more than adequately" },
  { word: "offer", meaning: "the verbal act of offering" },
  { word: "enter", meaning: "to come or go into" },
  { word: "favor", meaning: "an act of gracious kindness" },
  { word: "anode", meaning: "a positively charged electrode by which electrons leave an electrical device" },
  { word: "judge", meaning: "a public official authorized to decide questions brought before a court of justice" },
  { word: "model", meaning: "a hypothetical description of a complex entity or process" },
  { word: "solid", meaning: "matter that is solid at room temperature and pressure" },
  { word: "title", meaning: "the name of a work of art or literary composition etc." },
  { word: "knife", meaning: "edge tool used as a cutting instrument; has a pointed blade with a sharp edge and a handle" },
  { word: "quiet", meaning: "a period of calm weather" },
  { word: "round", meaning: "a charge of ammunition for a single shot" },
  { word: "frame", meaning: "the framework for a pair of eyeglasses" },
  { word: "store", meaning: "a mercantile establishment for the retail sale of goods or services" },
  { word: "brief", meaning: "a document stating the facts and points of law of a client's case" },
  { word: "allow", meaning: "make it possible through a specific action or lack of action for something to happen" },
  { word: "jones", meaning: "American naval commander in the American Revolution (1747-1792)" },
  { word: "legal", meaning: "established by or founded upon law or official or accepted rules" },
  { word: "phase", meaning: "any distinct time period in a sequence of events" },
  { word: "sharp", meaning: "a musical notation indicating one half step higher than the note named" },
  { word: "upper", meaning: "the higher of two berths" },
  { word: "april", meaning: "the month following March and preceding May" },
  { word: "forth", meaning: "from a particular thing or place or position (`forth' is obsolete)" },
  { word: "unity", meaning: "an undivided or unbroken completeness or totality with nothing wanting" },
  { word: "drawn", meaning: "cause to move by pulling" },
  { word: "china", meaning: "high quality porcelain originally made only in China" },
  { word: "clean", meaning: "a weightlift in which the barbell is lifted to shoulder height and then jerked overhead" },
  { word: "sweet", meaning: "English phonetician; one of the founders of modern phonetics (1845-1912)" },
  { word: "fifty", meaning: "the cardinal number that is the product of ten and five" },
  { word: "frank", meaning: "a smooth-textured sausage of minced beef or pork usually smoked; often served on a bread roll" },
  { word: "quick", meaning: "accomplished rapidly and without delay" },
  { word: "aside", meaning: "a message that departs from the main subject" },
  { word: "dress", meaning: "a one-piece garment for a woman; has skirt and bodice" },
  { word: "paris", meaning: "the capital and largest city of France; and international center of culture and commerce" },
  { word: "thick", meaning: "the location of something surrounded by other things" },
  { word: "birth", meaning: "the time when something begins (especially life)" },
  { word: "block", meaning: "a solid piece of something (usually having flat rectangular sides)" },
  { word: "chair", meaning: "a seat for one person, with a support for the back" },
  { word: "gross", meaning: "twelve dozen" },
  { word: "honor", meaning: "a tangible symbol signifying approval or distinction" },
  { word: "score", meaning: "a number or letter indicating quality (especially of a student's performance)" },
  { word: "sleep", meaning: "a natural and periodic state of rest during which consciousness of the world is suspended" },
  { word: "dream", meaning: "a series of mental images and emotions occurring during sleep" },
  { word: "empty", meaning: "a container that has been emptied" },
  { word: "rifle", meaning: "a shoulder firearm with a long barrel and a rifled bore" },
  { word: "drove", meaning: "a group of animals (a herd or flock) moving together" },
  { word: "beach", meaning: "an area of sand sloping down to the water of a sea or lake" },
  { word: "coast", meaning: "the shore of a sea or ocean" },
  { word: "greek", meaning: "the Hellenic branch of the Indo-European family of languages" },
  { word: "ideal", meaning: "the idea of something that is perfect; something that one hopes to attain" },
  { word: "metal", meaning: "cover with metal" },
  { word: "shore", meaning: "the land along the edge of a body of water" },
  { word: "armed", meaning: "prepare oneself for a military confrontation" },
  { word: "ended", meaning: "have an end, in a temporal, spatial, or quantitative sense; either spatial or metaphorical" },
  { word: "scale", meaning: "an ordered reference standard" },
  { word: "bible", meaning: "the sacred writings of the Christian religions" },
  { word: "exist", meaning: "have an existence, be extant" },
  { word: "novel", meaning: "an extended fictional work in prose; usually in the form of a story" },
  { word: "taste", meaning: "a strong liking" },
  { word: "avoid", meaning: "stay clear from; keep away from; keep out of the way of someone or something" },
  { word: "hence", meaning: "(used to introduce a logical conclusion) from that fact or reason or as a result" },
  { word: "minor", meaning: "a young person of either sex" },
  { word: "roman", meaning: "a resident of modern Rome" },
  { word: "smile", meaning: "change one's facial expression by spreading the lips, often to signal pleasure" },
  { word: "stone", meaning: "a lump or mass of hard consolidated mineral matter" },
  { word: "alive", meaning: "possessing life" },
  { word: "apart", meaning: "remote and separate physically or socially; ; - W.H.Hudson" },
  { word: "congo", meaning: "a major African river (one of the world's longest); flows through Congo into the South Atlantic" },
  { word: "shook", meaning: "a disassembled barrel; the parts packed for storage or shipment" },
  { word: "truck", meaning: "an automotive vehicle suitable for hauling" },
  { word: "truly", meaning: "in accordance with truth or fact or reality" },
  { word: "uncle", meaning: "the brother of your father or mother; the husband of your aunt" },
  { word: "apply", meaning: "be pertinent or relevant or applicable" },
  { word: "guess", meaning: "a message expressing an opinion based on incomplete evidence" },
  { word: "motor", meaning: "machine that converts other forms of energy into mechanical energy and so imparts motion" },
  { word: "spite", meaning: "feeling a need to see others suffer" },
  { word: "vital", meaning: "urgently needed; absolutely necessary" },
  { word: "wheel", meaning: "a handwheel that is used for steering" },
  { word: "cross", meaning: "a wooden structure consisting of an upright post with a transverse piece" },
  { word: "inner", meaning: "located inward; - Leonard Bernstein; - David Denby; - A.R.Gurney,Jr." },
  { word: "theme", meaning: "the subject matter of a conversation or discussion" },
  { word: "wagon", meaning: "van used by police to transport prisoners" },
  { word: "worry", meaning: "something or someone that causes anxiety; a source of unhappiness" },
  { word: "faced", meaning: "deal with (something unpleasant) head on" },
  { word: "phone", meaning: "get or try to get into communication (with someone) by telephone" },
  { word: "rural", meaning: "living in or characteristic of farming or country life" },
  { word: "smith", meaning: "religious leader who founded the Mormon Church in 1830 (1805-1844)" },
  { word: "chest", meaning: "box with a lid; used for storage; usually large and sturdy" },
  { word: "crowd", meaning: "a large number of things or people considered together" },
  { word: "depth", meaning: "the extent downward or backward or inward" },
  { word: "grass", meaning: "a police informer who implicates many people" },
  { word: "loose", meaning: "grant freedom to; free from confinement" },
  { word: "prove", meaning: "be shown or be found to be" },
  { word: "spend", meaning: "pass time in a specific way" },
  { word: "dozen", meaning: "the cardinal number that is the sum of eleven and one" },
  { word: "flesh", meaning: "the soft tissue of the body of a vertebrate: mainly muscle tissue and fat" },
  { word: "raise", meaning: "the amount a salary is increased" },
  { word: "trust", meaning: "something (as property) held by one party (the trustee) for the benefit of another (the beneficiary)" },
  { word: "agree", meaning: "be in accord; be in agreement" },
  { word: "angle", meaning: "move or proceed at an angle" },
  { word: "begun", meaning: "take the first step or steps in carrying out an action" },
  { word: "david", meaning: "patron saint of Wales (circa 520-600)" },
  { word: "chain", meaning: "a series of things depending on each other as if linked together" },
  { word: "extra", meaning: "an additional edition of a newspaper (usually to report a crisis)" },
  { word: "latin", meaning: "any dialect of the language of ancient Rome" },
  { word: "worse", meaning: "something inferior in quality or condition or effect" },
  { word: "count", meaning: "the total number counted" },
  { word: "anger", meaning: "a strong emotion; a feeling that is oriented toward some real or supposed grievance" },
  { word: "grand", meaning: "the cardinal number that is the product of 10 and 100" },
  { word: "guard", meaning: "a device designed to prevent injury or accidents" },
  { word: "hoped", meaning: "expect and wish" },
  { word: "limit", meaning: "the greatest possible degree of something" },
  { word: "plain", meaning: "extensive tract of level open land" },
  { word: "royal", meaning: "a sail set next above the topgallant on a royal mast" },
  { word: "sorry", meaning: "feeling or expressing regret or sorrow or a sense of loss over something done or undone" },
  { word: "swung", meaning: "move in a curve or arc, usually with the intent of hitting" },
  { word: "tired", meaning: "lose interest or become bored with something or somebody" },
  { word: "blind", meaning: "people who have severe visual impairments, considered as a group" },
  { word: "grant", meaning: "any monetary aid" },
  { word: "humor", meaning: "a message whose ingenuity or verbal skill or incongruity has the power to evoke laughter" },
  { word: "opera", meaning: "a commercial browser" },
  { word: "prior", meaning: "the head of a religious order; in an abbey the prior is next below the abbot" },
  { word: "award", meaning: "a grant made by a law court" },
  { word: "threw", meaning: "propel through the air" },
  { word: "trend", meaning: "a general direction in which something tends to move" },
  { word: "angry", meaning: "feeling or showing anger" },
  { word: "brain", meaning: "mental ability" },
  { word: "curve", meaning: "the trace of a point whose direction of motion changes" },
  { word: "prime", meaning: "the period of greatest prosperity or productivity" },
  { word: "sheet", meaning: "any broad thin expanse or surface" },
  { word: "steel", meaning: "a cutting or thrusting weapon that has a long metal blade and a hilt with a hand guard" },
  { word: "agent", meaning: "an active and efficient cause; capable of producing a certain effect" },
  { word: "brush", meaning: "a dense growth of bushes" },
  { word: "enjoy", meaning: "derive or receive pleasure from; get enjoyment from; take pleasure in" },
  { word: "fired", meaning: "start firing a weapon" },
  { word: "pilot", meaning: "a person qualified to guide ships through difficult waters going into or out of a harbor" },
  { word: "snake", meaning: "limbless scaly elongate reptile; some are venomous" },
  { word: "catch", meaning: "a drawback or difficulty that is not readily evident" },
  { word: "cloth", meaning: "artifact made by weaving or felting or knitting or crocheting natural or synthetic fibers" },
  { word: "drama", meaning: "an episode that is turbulent or highly emotional" },
  { word: "grown", meaning: "pass into a condition gradually, take on a specific property or attribute; become" },
  { word: "occur", meaning: "come to pass" },
  { word: "porch", meaning: "a structure attached to the exterior of a building often forming a covered entrance" },
  { word: "rapid", meaning: "done or occurring in a brief period of time" },
  { word: "route", meaning: "an established line of travel or access" },
  { word: "saved", meaning: "save from ruin, destruction, or harm" },
  { word: "bound", meaning: "a line determining the limits of an area" },
  { word: "hardy", meaning: "having rugged physical strength; inured to fatigue or hardships" },
  { word: "pride", meaning: "a feeling of self-respect and personal worth" },
  { word: "reply", meaning: "the speech act of continuing a conversational exchange" },
  { word: "skill", meaning: "an ability that has been acquired by training" },
  { word: "throw", meaning: "the act of throwing (propelling something with a rapid movement of the arm and wrist)" },
  { word: "wages", meaning: "a recompense for worthy acts or retribution for wrongdoing" },
  { word: "bread", meaning: "informal terms for money" },
  { word: "funny", meaning: "an account of an amusing incident (usually with a punch line)" },
  { word: "match", meaning: "a formal contest in which two or more persons or teams compete" },
  { word: "queen", meaning: "a female sovereign ruler" },
  { word: "rough", meaning: "the part of a golf course bordering the fairway where the grass is not cut short" },
  { word: "shift", meaning: "an event in which something is displaced without rotation" },
  { word: "smoke", meaning: "a cloud of fine particles suspended in a gas" },
  { word: "teach", meaning: "impart skills or knowledge to" },
  { word: "focus", meaning: "the concentration of attention or energy on something" },
  { word: "grace", meaning: "elegance and beauty of movement or expression" },
  { word: "proof", meaning: "any factual evidence that helps to establish the truth of something" },
  { word: "shear", meaning: "a large edge tool that cuts sheet metal by passing a blade through it" },
  { word: "guest", meaning: "a visitor to whom hospitality is extended" },
  { word: "joint", meaning: "a disreputable place of entertainment" },
  { word: "stick", meaning: "an implement consisting of a length of wood" },
  { word: "fifth", meaning: "position five in a countable series of things" },
  { word: "japan", meaning: "lacquerware decorated and varnished in the Japanese manner with a glossy durable black lacquer" },
  { word: "onset", meaning: "the beginning or early stages" },
  { word: "piano", meaning: "(music) low loudness" },
  { word: "track", meaning: "a line or route along which something travels or moves" },
  { word: "turns", meaning: "a circular segment of a curve" },
  { word: "admit", meaning: "declare to be true or admit the existence or reality or truth of" },
  { word: "chose", meaning: "pick out, select, or choose from a number of alternatives" },
  { word: "drunk", meaning: "a chronic drinker" },
  { word: "magic", meaning: "any art that invokes supernatural powers" },
  { word: "mixed", meaning: "mix together different elements" },
  { word: "noise", meaning: "sound of any kind (especially unintelligible or dissonant sound)" },
  { word: "paint", meaning: "makeup consisting of a pink or red powder applied to the cheeks" },
  { word: "dirty", meaning: "make soiled, filthy, or dirty" },
  { word: "error", meaning: "a wrong action attributable to bad judgment or ignorance or inattention" },
  { word: "forty", meaning: "the cardinal number that is the product of ten and four" },
  { word: "guide", meaning: "someone employed to conduct others" },
  { word: "hurry", meaning: "overly eager speed (and possible carelessness)" },
  { word: "lying", meaning: "the deliberate act of deviating from the truth" },
  { word: "maris", meaning: "the Finnic language spoken by the Cheremis" },
  { word: "peter", meaning: "obscene terms for penis" },
  { word: "ratio", meaning: "the relative magnitudes of two quantities (usually expressed as a quotient)" },
  { word: "thank", meaning: "express gratitude or show appreciation to" },
  { word: "tough", meaning: "an aggressive and violent young criminal" },
  { word: "bench", meaning: "a long seat for more than one person" },
  { word: "crime", meaning: "(criminal law) an act punishable by law; usually considered an evil act" },
  { word: "fruit", meaning: "the ripened reproductive body of a seed plant" },
  { word: "grade", meaning: "a body of students who are taught together" },
  { word: "harry", meaning: "annoy continually or chronically" },
  { word: "waste", meaning: "any materials unused and rejected as worthless or unwanted" },
  { word: "yield", meaning: "production of a certain amount" },
  { word: "badly", meaning: "to a severe or serious degree" },
  { word: "blame", meaning: "an accusation that you are responsible for some lapse or misdeed" },
  { word: "clerk", meaning: "an employee who performs clerical work (e.g., keeps records or accounts)" },
  { word: "crazy", meaning: "someone deranged and possibly dangerous" },
  { word: "dying", meaning: "the time when something ends" },
  { word: "ocean", meaning: "a large body of water constituting a principal part of the hydrosphere" },
  { word: "smell", meaning: "the general atmosphere of a place or situation and the effect that it has on people" },
  { word: "sugar", meaning: "a white crystalline carbohydrate used as a sweetener and preservative" },
  { word: "swept", meaning: "sweep across or over" },
  { word: "worst", meaning: "the least favorable outcome" },
  { word: "alert", meaning: "condition of heightened watchfulness or preparation for action" },
  { word: "bride", meaning: "a woman who has recently been married" },
  { word: "burst", meaning: "the act of exploding or bursting" },
  { word: "drill", meaning: "similar to the mandrill but smaller and less brightly colored" },
  { word: "grave", meaning: "death of a person" },
  { word: "guilt", meaning: "the state of having committed an offense" },
  { word: "leads", meaning: "an advantage held by a competitor in a race" },
  { word: "lunch", meaning: "a midday meal" },
  { word: "naval", meaning: "connected with or belonging to or used in a navy" },
  { word: "swift", meaning: "a small bird that resembles a swallow and is noted for its rapid flight" },
  { word: "naked", meaning: "completely unclothed" },
  { word: "stuff", meaning: "the tangible substance that goes into the makeup of a physical object" },
  { word: "outer", meaning: "being on the outside or further from a center" },
  { word: "panel", meaning: "sheet that forms a distinct (usually flat and rectangular) section or component of something" },
  { word: "shock", meaning: "the feeling of distress and disbelief that you have when something bad happens accidentally" },
  { word: "trail", meaning: "a track or mark left by something that has passed" },
  { word: "cried", meaning: "utter a sudden loud cry" },
  { word: "fence", meaning: "a barrier that serves to enclose an area" },
  { word: "slave", meaning: "someone entirely dominated by some influence or person" },
  { word: "split", meaning: "extending the legs at right angles to the trunk (one in front and the other in back)" },
  { word: "strip", meaning: "a relatively long narrow piece of something" },
  { word: "argue", meaning: "present reasons and arguments" },
  { word: "false", meaning: "not in accordance with the fact or reality or actuality" },
  { word: "merit", meaning: "any admirable quality or attribute" },
  { word: "arise", meaning: "come into existence; take on form or shape" },
  { word: "cloud", meaning: "any collection of particles (e.g., smoke or dust) or gases that is visible" },
  { word: "dried", meaning: "remove the moisture from and make dry" },
  { word: "irish", meaning: "people of Ireland or of Irish extraction" },
  { word: "laugh", meaning: "the sound of laughing" },
  { word: "mines", meaning: "excavation in the earth from which ores and minerals are extracted" },
  { word: "newly", meaning: "very recently" },
  { word: "pound", meaning: "16 ounces avoirdupois" },
  { word: "prize", meaning: "something given for victory or superiority in a contest or competition or for winning a lottery" },
  { word: "shade", meaning: "relative darkness caused by light rays being intercepted by an opaque body" },
  { word: "tight", meaning: "closely constrained or constricted or constricting" },
  { word: "verse", meaning: "literature in metrical form" },
  { word: "wound", meaning: "an injury to living tissue (especially an injury involving a cut or break in the skin)" },
  { word: "eager", meaning: "having or showing keen interest or intense desire or impatient expectancy" },
  { word: "exact", meaning: "claim as due or just" },
  { word: "fiber", meaning: "a slender and greatly elongated substance capable of being spun into yarn" },
  { word: "grain", meaning: "a relatively small granular particle of a substance" },
  { word: "ranch", meaning: "manage or run a ranch" },
  { word: "refer", meaning: "make reference to" },
  { word: "scope", meaning: "an area in which something acts or operates or has power or control:" },
  { word: "shirt", meaning: "a garment worn on the upper half of the body" },
  { word: "shoot", meaning: "a new branch" },
  { word: "suite", meaning: "a musical composition of several movements only loosely connected" },
  { word: "beard", meaning: "the hair growing on the lower part of a man's face" },
  { word: "billy", meaning: "a short stout club used primarily by policemen" },
  { word: "charm", meaning: "attractiveness that interests or pleases or stimulates" },
  { word: "entry", meaning: "an item inserted in a written record" },
  { word: "mount", meaning: "a lightweight horse kept for riding only" },
  { word: "sarah", meaning: "(Old Testament) the wife of Abraham and mother of Isaac" },
  { word: "sixth", meaning: "position six in a countable series of things" },
  { word: "storm", meaning: "a violent commotion or disturbance" },
  { word: "treat", meaning: "something considered choice to eat" },
  { word: "widow", meaning: "a woman whose husband is dead especially one who has not remarried" },
  { word: "adult", meaning: "a fully developed person from maturity onward" },
  { word: "devil", meaning: "an evil supernatural being" },
  { word: "faint", meaning: "a spontaneous loss of consciousness caused by insufficient blood to the brain" },
  { word: "hired", meaning: "engage or hire for work" },
  { word: "honey", meaning: "a sweet yellow liquid produced by bees" },
  { word: "penny", meaning: "a fractional monetary unit of Ireland and the United Kingdom; equal to one hundredth of a pound" },
  { word: "vague", meaning: "not clearly understood or expressed; ; -Anatole Broyard; - P.A.Sorokin; - John Locke" },
  { word: "vivid", meaning: "having the clarity and freshness of immediate experience" },
  { word: "actor", meaning: "a theatrical performer" },
  { word: "brave", meaning: "a North American Indian warrior" },
  { word: "cheap", meaning: "relatively low in price or charging low prices" },
  { word: "coach", meaning: "(sports) someone in charge of training an athlete or a team" },
  { word: "cycle", meaning: "an interval during which a recurring sequence of events occurs" },
  { word: "draft", meaning: "a document ordering the payment of money; drawn by one person or bank on another" },
  { word: "mason", meaning: "a craftsman who works with stone or brick" },
  { word: "moore", meaning: "British sculptor whose works are monumental organic forms (1898-1986)" },
  { word: "motel", meaning: "a motor hotel" },
  { word: "rigid", meaning: "incapable of or resistant to bending" },
  { word: "swing", meaning: "a state of steady vigorous action that is characteristic of an activity" },
  { word: "bases", meaning: "installation from which a military force initiates operations" },
  { word: "belly", meaning: "the region of the body of a vertebrate between the thorax and the pelvis" },
  { word: "bobby", meaning: "an informal term for a British policeman" },
  { word: "cabin", meaning: "small room on a ship or boat where people sleep" },
  { word: "civic", meaning: "of or relating to or befitting citizens as individuals" },
  { word: "craft", meaning: "the skilled practice of a practical occupation" },
  { word: "giant", meaning: "any creature of exceptional size" },
  { word: "habit", meaning: "an established custom" },
  { word: "noble", meaning: "a titled peer of the realm" },
  { word: "sheep", meaning: "woolly usually horned ruminant mammal related to the goat" },
  { word: "spare", meaning: "an extra component of a machine or other apparatus" },
  { word: "stern", meaning: "the rear part of a ship" },
  { word: "stuck", meaning: "put, fix, force, or implant" },
  { word: "sweat", meaning: "salty fluid secreted by sweat glands" },
  { word: "trace", meaning: "a just detectable amount" },
  { word: "blues", meaning: "a state of depression" },
  { word: "chart", meaning: "a visual display of information" },
  { word: "dealt", meaning: "act on verbally or in some form of artistic expression" },
  { word: "fault", meaning: "a wrong action attributable to bad judgment or ignorance or inattention" },
  { word: "panic", meaning: "an overwhelming feeling of fear and anxiety" },
  { word: "pitch", meaning: "the property of sound that varies with variation in the frequency of vibration" },
  { word: "plate", meaning: "a sheet of metal or wood or glass or plastic" },
  { word: "shell", meaning: "the material that forms the hard outer covering of many animals" },
  { word: "valid", meaning: "well grounded in logic or truth or having legal force" },
  { word: "crack", meaning: "a long narrow opening" },
  { word: "delay", meaning: "time during which some action is awaited" },
  { word: "flash", meaning: "a sudden intense burst of radiant energy" },
  { word: "fluid", meaning: "a substance that is fluid at room temperature and pressure" },
  { word: "glory", meaning: "a state of high honor" },
  { word: "lucky", meaning: "occurring by chance" },
  { word: "pause", meaning: "a time interval during which there is a temporary cessation of something" },
  { word: "screw", meaning: "a propeller with several angled blades that rotates to push against water or air" },
  { word: "shame", meaning: "a painful emotion resulting from an awareness of inadequacy or guilt" },
  { word: "sixty", meaning: "the cardinal number that is the product of ten and six" },
  { word: "skirt", meaning: "cloth covering that forms the part of a garment below the waist" },
  { word: "smart", meaning: "a kind of pain such as that caused by a wound or a burn or a sore" },
  { word: "stiff", meaning: "an ordinary man" },
  { word: "tales", meaning: "a trivial lie" },
  { word: "alike", meaning: "having the same or similar characteristics" },
  { word: "awake", meaning: "stop sleeping" },
  { word: "boots", meaning: "footwear that covers the whole foot and lower leg" },
  { word: "cheek", meaning: "either side of the face below the eyes" },
  { word: "clock", meaning: "a timepiece that shows the time of day" },
  { word: "crash", meaning: "a loud resonant repeating noise" },
  { word: "cream", meaning: "the best people or things in a group" },
  { word: "input", meaning: "signal going into an electronic system" },
  { word: "lobby", meaning: "a large entrance or reception room or area" },
  { word: "mercy", meaning: "a disposition to be kind and forgiving" },
  { word: "ninth", meaning: "position nine in a countable series of things" },
  { word: "pupil", meaning: "a learner who is enrolled in an educational institution" },
  { word: "sauce", meaning: "flavorful relish or dressing or topping served as an accompaniment to food" },
  { word: "slide", meaning: "a small flat rectangular piece of glass on which specimens can be mounted for microscopic study" },
  { word: "solve", meaning: "find the solution to (a problem or question) or understand the meaning of" },
  { word: "stake", meaning: "(law) a right or legal share of something; a financial involvement with something" },
  { word: "tooth", meaning: "toothlike structure in invertebrates found in the mouth or alimentary canal or on a shell" },
  { word: "brass", meaning: "an alloy of copper and zinc" },
  { word: "crown", meaning: "the part of a tooth above the gum that is covered with enamel" },
  { word: "cuban", meaning: "a native or inhabitant of Cuba" },
  { word: "dairy", meaning: "a farm where dairy products are produced" },
  { word: "drank", meaning: "take in liquids" },
  { word: "essay", meaning: "an analytic or interpretive literary composition" },
  { word: "fatal", meaning: "bringing death" },
  { word: "fever", meaning: "a rise in the temperature of the body; frequently a symptom of infection" },
  { word: "flood", meaning: "the rising of a body of water and its overflowing onto normally dry land" },
  { word: "gains", meaning: "a quantity that is added" },
  { word: "glued", meaning: "join or attach with or as if with glue" },
  { word: "label", meaning: "a brief description given for purposes of identification" },
  { word: "letch", meaning: "man with strong sexual desires" },
  { word: "lodge", meaning: "a formal association of people with similar interests" },
  { word: "lover", meaning: "an ardent follower and admirer" },
  { word: "midst", meaning: "the location of something surrounded by other things" },
  { word: "naive", meaning: "marked by or showing unaffected simplicity and lack of guile or worldly experience" },
  { word: "realm", meaning: "a domain in which something is dominant" },
  { word: "relax", meaning: "become less tense, rest, or take one's ease" },
  { word: "slope", meaning: "an elevated geological formation" },
  { word: "sober", meaning: "cause to become sober" },
  { word: "spell", meaning: "a psychological state induced by (or as if induced by) a magical incantation" },
  { word: "toast", meaning: "slices of bread that have been toasted" },
  { word: "abuse", meaning: "cruel or inhumane treatment" },
  { word: "angel", meaning: "spiritual being attendant upon God" },
  { word: "arose", meaning: "come into existence; take on form or shape" },
  { word: "brick", meaning: "rectangular block of clay baked by the sun or in a kiln; used as a building or paving material" },
  { word: "chase", meaning: "the act of pursuing in an effort to overtake or capture" },
  { word: "drain", meaning: "emptying something accomplished by allowing liquid to run out of it" },
  { word: "drift", meaning: "a force that moves something along" },
  { word: "faded", meaning: "become less clearly visible or distinguishable; disappear gradually or seemingly" },
  { word: "lemon", meaning: "yellow oval fruit with juicy acidic flesh" },
  { word: "loyal", meaning: "steadfast in allegiance or duty" },
  { word: "marry", meaning: "take in marriage" },
  { word: "print", meaning: "the text appearing in a book, newspaper, or other printed publication" },
  { word: "rebel", meaning: "take part in a rebellion; renounce a former allegiance" },
  { word: "ridge", meaning: "a long narrow natural elevation or striation" },
  { word: "serum", meaning: "an amber, watery fluid, rich in proteins, that separates out when blood coagulates" },
  { word: "squad", meaning: "a smallest army unit" },
  { word: "stall", meaning: "a compartment in a stable where a single animal is confined and fed" },
  { word: "stein", meaning: "a mug intended for serving beer" },
  { word: "twist", meaning: "an unforeseen development" },
  { word: "awful", meaning: "exceptionally bad or displeasing" },
  { word: "brand", meaning: "a name given to a product or service" },
  { word: "breed", meaning: "a special variety of domesticated animals within a species" },
  { word: "bunch", meaning: "a grouping of a number of similar things" },
  { word: "chaos", meaning: "a state of extreme confusion and disorder" },
  { word: "dandy", meaning: "a man who is much concerned with his dress and appearance" },
  { word: "flame", meaning: "the process of combustion of inflammable materials producing heat and light and (often) smoke" },
  { word: "fleet", meaning: "group of aircraft operating together under the same ownership" },
  { word: "graph", meaning: "represent by means of a graph" },
  { word: "grasp", meaning: "understanding of the nature or meaning or quality or magnitude of something" },
  { word: "ivory", meaning: "a hard smooth ivory colored dentine that makes up most of the tusks of elephants and walruses" },
  { word: "logic", meaning: "the branch of philosophy that analyzes inference" },
  { word: "nurse", meaning: "a woman who is the custodian of children" },
  { word: "quote", meaning: "a punctuation mark used to attribute the enclosed text to someone else" },
  { word: "shake", meaning: "building material used as siding or roofing" },
  { word: "sport", meaning: "an active diversion requiring physical exertion and competition" },
  { word: "steam", meaning: "water at boiling temperature diffused in the atmosphere" },
  { word: "tract", meaning: "an extended area of land" },
  { word: "tumor", meaning: "an abnormal new mass of tissue that serves no purpose" },
  { word: "weary", meaning: "exhaust or get tired through overuse or great strain or stress" },
  { word: "alarm", meaning: "fear resulting from the awareness of danger" },
  { word: "alien", meaning: "anyone who does not belong in the environment in which they are found" },
  { word: "ample", meaning: "more than enough in size or scope or capacity" },
  { word: "attic", meaning: "floor consisting of open space at the top of a house just below roof; often used for storage" },
  { word: "candy", meaning: "a rich sweet made of flavored sugar and often combined with fruit or nuts" },
  { word: "dusty", meaning: "covered with a layer of dust" },
  { word: "fancy", meaning: "something many people believe that is false" },
  { word: "homer", meaning: "a base hit on which the batter scores a run" },
  { word: "lined", meaning: "be in line with; form a line along" },
  { word: "liver", meaning: "having a reddish-brown color" },
  { word: "opium", meaning: "an addictive narcotic extracted from seed capsules of the opium poppy" },
  { word: "orbit", meaning: "the (usually elliptical) path described by one celestial body in its revolution about another" },
  { word: "piled", meaning: "arrange in stacks" },
  { word: "quest", meaning: "a search for an alternative that meets cognitive criteria" },
  { word: "rider", meaning: "a clause that is appended to a legislative bill" },
  { word: "saint", meaning: "person of exceptional holiness" },
  { word: "scott", meaning: "British author of historical novels and ballads (1771-1832)" },
  { word: "solar", meaning: "relating to or derived from the sun or utilizing the energies of the sun" },
  { word: "spray", meaning: "a pesticide in suspension or solution; intended for spraying" },
  { word: "troop", meaning: "a group of soldiers" },
  { word: "waved", meaning: "signal with the hands or nod" },
  { word: "alter", meaning: "cause to change; make different; cause a transformation" },
  { word: "blast", meaning: "a very long fly ball" },
  { word: "boost", meaning: "the act of giving hope or support to someone" },
  { word: "cease", meaning: "(`cease' is a noun only in the phrase `without cease') end" },
  { word: "crude", meaning: "a dark oil consisting mainly of hydrocarbons" },
  { word: "cruel", meaning: "(of persons or their actions) able or disposed to inflict pain or suffering" },
  { word: "cubic", meaning: "having three dimensions" },
  { word: "dutch", meaning: "the people of the Netherlands" },
  { word: "elder", meaning: "any of various church officers" },
  { word: "knock", meaning: "negative criticism" },
  { word: "onion", meaning: "the bulb of an onion plant" },
  { word: "razor", meaning: "edge tool used in shaving" },
  { word: "react", meaning: "show a response or a reaction to something" },
  { word: "sheer", meaning: "turn sharply; change direction abruptly" },
  { word: "silly", meaning: "a word used for misbehaving children" },
  { word: "stove", meaning: "any heating apparatus" },
  { word: "straw", meaning: "a variable yellow tint; dull yellow, often diluted with white" },
  { word: "sweep", meaning: "a wide scope" },
  { word: "tense", meaning: "a grammatical category of verbs used to express distinctions of time" },
  { word: "trick", meaning: "a cunning or deceitful action or device" },
  { word: "arrow", meaning: "a mark to indicate a direction or relation" },
  { word: "blank", meaning: "a blank character used to separate successive words in writing or printing" },
  { word: "brace", meaning: "a support that steadies or strengthens something else" },
  { word: "chill", meaning: "coldness due to a cold environment" },
  { word: "chuck", meaning: "informal terms for a meal" },
  { word: "clung", meaning: "come or be in close contact with; stick or hold together and resist separation" },
  { word: "debut", meaning: "the act of beginning something new" },
  { word: "decay", meaning: "the process of gradually becoming inferior" },
  { word: "flung", meaning: "throw with force or recklessness" },
  { word: "gloom", meaning: "a state of partial or total darkness" },
  { word: "grove", meaning: "a small growth of trees without underbrush" },
  { word: "iliad", meaning: "a Greek epic poem (attributed to Homer) describing the siege of Troy" },
  { word: "lever", meaning: "a rigid bar pivoted about a fulcrum" },
  { word: "prone", meaning: "having a tendency (to); often used in combination" },
  { word: "prose", meaning: "ordinary writing as distinguished from verse" },
  { word: "purse", meaning: "a container used for carrying money and small personal items or accessories (especially by women)" },
  { word: "stare", meaning: "a fixed look with eyes open wide" },
  { word: "swiss", meaning: "the natives or inhabitants of Switzerland" },
  { word: "swore", meaning: "utter obscenities or profanities" },
  { word: "upset", meaning: "an unhappy and worried mental state" },
  { word: "usage", meaning: "the act of using" },
  { word: "vigor", meaning: "forceful exertion" },
  { word: "vocal", meaning: "music intended to be performed by one or more singers, usually with instrumental accompaniment" },
  { word: "width", meaning: "the extent of something from side to side" },
  { word: "acute", meaning: "a mark (') placed above a vowel to indicate pronunciation" },
  { word: "adopt", meaning: "choose and follow; as of theories, ideas, policies, strategies or plans" },
  { word: "aloud", meaning: "using the voice; not silently" },
  { word: "blade", meaning: "especially a leaf of grass or the broad portion of a leaf as distinct from the petiole" },
  { word: "buddy", meaning: "a close friend who accompanies his buddies in their activities" },
  { word: "depot", meaning: "station where transport vehicles load or unload passengers or goods" },
  { word: "dough", meaning: "a flour mixture stiff enough to knead or roll" },
  { word: "elite", meaning: "a group or class of persons enjoying superior intellectual or social or economic status" },
  { word: "erect", meaning: "construct, build, or erect" },
  { word: "globe", meaning: "the 3rd planet from the sun; the planet we live on" },
  { word: "handy", meaning: "easy to reach" },
  { word: "hymen", meaning: "(Greek mythology) the god of marriage" },
  { word: "imply", meaning: "express or state indirectly" },
  { word: "media", meaning: "a means or instrumentality for storing or communicating information" },
  { word: "patch", meaning: "a small contrasting part of something" },
  { word: "rabbi", meaning: "spiritual leader of a Jewish congregation; qualified to expound and apply Jewish law" },
  { word: "sally", meaning: "witty remark" },
  { word: "slice", meaning: "a share of something" },
  { word: "steep", meaning: "a steep place (as on a hill)" },
  { word: "sunny", meaning: "bright and pleasant; promoting a feeling of cheer" },
  { word: "taxed", meaning: "levy a tax on" },
  { word: "tower", meaning: "a structure taller than its diameter; can stand alone or be attached to a larger building" },
  { word: "undue", meaning: "not yet payable" },
  { word: "utter", meaning: "articulate; either verbally or with a cry, shout, or noise" },
  { word: "virus", meaning: "a harmful or corrupting agency" },
  { word: "atlas", meaning: "(Greek mythology) a Titan who was forced by Zeus to bear the sky on his shoulders" },
  { word: "bloom", meaning: "the organic process of bearing flowers" },
  { word: "climb", meaning: "an upward slope or grade (as in a road)" },
  { word: "couch", meaning: "an upholstered seat for more than one person" },
  { word: "crest", meaning: "the top line of a hill, mountain, or wave" },
  { word: "dimly", meaning: "in a dim indistinct manner" },
  { word: "eaten", meaning: "take in solid food" },
  { word: "freed", meaning: "grant freedom to; free from confinement" },
  { word: "gauge", meaning: "the distance between the rails of a railway or between the wheels of a train" },
  { word: "grill", meaning: "a restaurant where food is cooked on a grill" },
  { word: "harsh", meaning: "unpleasantly stern" },
  { word: "irony", meaning: "witty language used to convey insults or scorn; ; ; --Jonathan Swift" },
  { word: "layer", meaning: "single thickness of usually some homogeneous substance" },
  { word: "lyric", meaning: "the text of a popular song or musical-comedy number" },
  { word: "maker", meaning: "terms referring to the Judeo-Christian God" },
  { word: "maria", meaning: "a dark region of considerable extent on the surface of the moon" },
  { word: "nerve", meaning: "any bundle of nerve fibers running to various organs and tissues of the body" },
  { word: "organ", meaning: "a government agency or instrument devoted to the performance of some specific function" },
  { word: "phony", meaning: "fraudulent; having a misleading appearance" },
  { word: "rival", meaning: "the contestant you hope to defeat" },
  { word: "sadly", meaning: "in an unfortunate way" },
  { word: "shelf", meaning: "a support that consists of a horizontal surface for holding objects" },
  { word: "sizes", meaning: "the physical magnitude of something (how big it is)" },
  { word: "skies", meaning: "the atmosphere and outer space as viewed from the earth" },
  { word: "spark", meaning: "a momentary flash of light" },
  { word: "stray", meaning: "move about aimlessly or without any destination, often in search of food or employment" },
  { word: "vapor", meaning: "a visible suspension in the air of particles of some substance" },
  { word: "wayne", meaning: "American general during the American Revolution (1745-1796)" },
  { word: "array", meaning: "an orderly arrangement" },
  { word: "cliff", meaning: "a steep high face of rock" },
  { word: "crawl", meaning: "a very slow movement" },
  { word: "crept", meaning: "move slowly; in the case of people or animals with the body near the ground" },
  { word: "curse", meaning: "profane or obscene expression usually of surprise or anger" },
  { word: "dodge", meaning: "an elaborate or deceitful scheme contrived to deceive or evade" },
  { word: "ferry", meaning: "a boat that transports people or vehicles across a body of water and operates on a regular schedule" },
  { word: "flush", meaning: "the period of greatest prosperity or productivity" },
  { word: "ghost", meaning: "a mental representation of some haunting experience" },
  { word: "glaze", meaning: "any of various thin shiny (savory or sweet) coatings applied to foods" },
  { word: "hogan", meaning: "a Navajo lodge covered with earth; traditionally built with the entrance facing east" },
  { word: "jimmy", meaning: "a short crowbar" },
  { word: "juice", meaning: "the liquid part that can be extracted from plant or animal tissue by squeezing or cooking" },
  { word: "moist", meaning: "slightly wet" },
  { word: "mound", meaning: "a small natural hill" },
  { word: "overt", meaning: "open and observable; not secret or hidden" },
  { word: "paced", meaning: "walk with slow or fast paces" },
  { word: "posse", meaning: "a temporary police force" },
  { word: "quint", meaning: "the cardinal number that is the sum of four and one" },
  { word: "shaft", meaning: "a line that forms the length of an arrow pointer" },
  { word: "venus", meaning: "goddess of love; counterpart of Greek Aphrodite" },
  { word: "viola", meaning: "a bowed stringed instrument slightly larger than a violin, tuned a fifth lower" },
  { word: "waist", meaning: "the narrowing of the body between the ribs and hips" },
  { word: "wired", meaning: "provide with electrical circuits" },
];

export default WORDS;